buildpack:
  name: Blazar-Buildpack-Java-single-module

enabled: true

env:
  SET_VERSION_OVERRIDE: 1.0-$GIT_BRANCH-SNAPSHOT
  MAVEN_ARGS: -DskipTests -am -pl revapi-java,revapi-reporter-text,revapi-java-spi,revapi-standalone


provides:
  - name: revapi
    version: 1.0-$GIT_BRANCH-SNAPSHOT
